parameters:
#    ulb_clbase_browse.example.class: Ulb\Clbase\BrowseBundle\Example

services:
#    ulb_clbase_browse.example:
#        class: %ulb_clbase_browse.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
